in nested raise function
raising exception (something happened)
in exception handler
oops something happened
nil
