class MyException < Exception {
    init(msg) {
        super.init(msg)
        this.name="MyException"
    }
}


try {
    var a=1
    var b=2
    print "hello"
    try {
        var a=1
        var b=2
        print "hello inner"
        print "inner raising Exception (something happened)"
        raise Exception("inner something happened")
    }
    except MyException as e {
        var x=2
        print "in inner MyException handler"
        print "oops "+e.name+" "+str(e)
    }
    except Exception as e {
        var x=2
        print "in inner Exception handler"
        print "oops "+e.name+" "+str(e)
    }

    print "raising Exception (outer something happened)"
    raise Exception("outer something happened")
}
except MyException as e {
    var x=2
    print "in outer MyException handler"
    print "oops "+e.name+" "+str(e)
}
 except Exception as e {
        var x=2
        print "in outer Exception handler"
        print "oops "+e.name+" "+str(e)
    }

